
stages:
  - package
  - deploy

build_image:
  stage: package
  image: docker:stable

  services:
    - docker:dind

  only:
    - main
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t pwa:dev .
    - docker tag pwa:dev giktekio/ecobank-pwa:dev.v1.0.4
    - docker push giktekio/ecobank-pwa:dev.v1.0.4

